### ISSUE TITLE
Invalid slides URL

### ISSUE THREAD

**Issue by jnv** [myguidingstar/infoq-downloader#1]
It seems InfoQ moved slides images to a CDN on a separate domain, so the casper script generates incorrect URLs like this:

```
http://www.infoq.comhttp://cdn.infoq.com/statics_s2_…
```

The fix is to simply remove concatenation in [slide->aria2-lines](https://github.com/myguidingstar/infoq-downloader/blob/c1c0539f484926d2778b1b2b2c5df0450ca7ed7b/src/infoq-casper.cl2#L105), however I'm not sure whether this is the case with all videos, or just newer ones. Maybe add a filter to check whether the URL is absolute?

**Comment by myguidingstar-zz** [comment]
Fixed
